language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pylint
# command to run tests
script:
  - # find idseq_pipeline -name '*.py' | xargs pylint -E
